package com.endreborn.endreborn.registry;

import com.endreborn.endreborn.EndReborn;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.world.level.block.SoundType;

/** Sound events + custom block SoundTypes (generated by tools/stage6_sounds.py). */
public final class ModSounds {
    private ModSounds() {}

    private static SoundEvent event(String name) {
        Identifier id = EndReborn.id(name);
        return Registry.register(BuiltInRegistries.SOUND_EVENT, id, SoundEvent.createVariableRangeEvent(id));
    }

    public static final SoundEvent VOID_MOTH_AMBIENT = event("entity.endreborn.void_moth.ambient");
    public static final SoundEvent VOID_MOTH_HURT = event("entity.endreborn.void_moth.hurt");
    public static final SoundEvent VOID_MOTH_DEATH = event("entity.endreborn.void_moth.death");
    public static final SoundEvent CHORUS_SPRITE_AMBIENT = event("entity.endreborn.chorus_sprite.ambient");
    public static final SoundEvent CHORUS_SPRITE_HURT = event("entity.endreborn.chorus_sprite.hurt");
    public static final SoundEvent CHORUS_SPRITE_DEATH = event("entity.endreborn.chorus_sprite.death");
    public static final SoundEvent CRYSTAL_STRIDER_AMBIENT = event("entity.endreborn.crystal_strider.ambient");
    public static final SoundEvent CRYSTAL_STRIDER_HURT = event("entity.endreborn.crystal_strider.hurt");
    public static final SoundEvent CRYSTAL_STRIDER_DEATH = event("entity.endreborn.crystal_strider.death");
    public static final SoundEvent VOID_WRAITH_AMBIENT = event("entity.endreborn.void_wraith.ambient");
    public static final SoundEvent VOID_WRAITH_HURT = event("entity.endreborn.void_wraith.hurt");
    public static final SoundEvent VOID_WRAITH_DEATH = event("entity.endreborn.void_wraith.death");
    public static final SoundEvent OBSIDIAN_GOLEM_AMBIENT = event("entity.endreborn.obsidian_golem.ambient");
    public static final SoundEvent OBSIDIAN_GOLEM_HURT = event("entity.endreborn.obsidian_golem.hurt");
    public static final SoundEvent OBSIDIAN_GOLEM_DEATH = event("entity.endreborn.obsidian_golem.death");
    public static final SoundEvent ABYSS_STALKER_AMBIENT = event("entity.endreborn.abyss_stalker.ambient");
    public static final SoundEvent ABYSS_STALKER_HURT = event("entity.endreborn.abyss_stalker.hurt");
    public static final SoundEvent ABYSS_STALKER_DEATH = event("entity.endreborn.abyss_stalker.death");
    public static final SoundEvent CRYSTAL_SENTINEL_AMBIENT = event("entity.endreborn.crystal_sentinel.ambient");
    public static final SoundEvent CRYSTAL_SENTINEL_HURT = event("entity.endreborn.crystal_sentinel.hurt");
    public static final SoundEvent CRYSTAL_SENTINEL_DEATH = event("entity.endreborn.crystal_sentinel.death");
    public static final SoundEvent CRYSTAL_SENTINEL_ZAP = event("entity.endreborn.crystal_sentinel.zap");
    public static final SoundEvent CHORUS_GUARDIAN_AMBIENT = event("entity.endreborn.chorus_guardian.ambient");
    public static final SoundEvent CHORUS_GUARDIAN_HURT = event("entity.endreborn.chorus_guardian.hurt");
    public static final SoundEvent CHORUS_GUARDIAN_DEATH = event("entity.endreborn.chorus_guardian.death");
    public static final SoundEvent CHORUS_GUARDIAN_ROAR = event("entity.endreborn.chorus_guardian.roar");
    public static final SoundEvent VOIDBRINGER_AMBIENT = event("entity.endreborn.voidbringer.ambient");
    public static final SoundEvent VOIDBRINGER_HURT = event("entity.endreborn.voidbringer.hurt");
    public static final SoundEvent VOIDBRINGER_DEATH = event("entity.endreborn.voidbringer.death");
    public static final SoundEvent VOIDBRINGER_ROAR = event("entity.endreborn.voidbringer.roar");
    public static final SoundEvent VOID_STONE_BREAK = event("block.endreborn.void_stone.break");
    public static final SoundEvent VOID_STONE_STEP = event("block.endreborn.void_stone.step");
    public static final SoundEvent VOID_STONE_PLACE = event("block.endreborn.void_stone.place");
    public static final SoundEvent VOID_STONE_HIT = event("block.endreborn.void_stone.hit");
    public static final SoundEvent VOID_STONE_FALL = event("block.endreborn.void_stone.fall");
    public static final SoundEvent CRYSTAL_BREAK = event("block.endreborn.crystal.break");
    public static final SoundEvent CRYSTAL_STEP = event("block.endreborn.crystal.step");
    public static final SoundEvent CRYSTAL_PLACE = event("block.endreborn.crystal.place");
    public static final SoundEvent CRYSTAL_HIT = event("block.endreborn.crystal.hit");
    public static final SoundEvent CRYSTAL_FALL = event("block.endreborn.crystal.fall");
    public static final SoundEvent OBSIDIAN_BREAK = event("block.endreborn.obsidian.break");
    public static final SoundEvent OBSIDIAN_STEP = event("block.endreborn.obsidian.step");
    public static final SoundEvent OBSIDIAN_PLACE = event("block.endreborn.obsidian.place");
    public static final SoundEvent OBSIDIAN_HIT = event("block.endreborn.obsidian.hit");
    public static final SoundEvent OBSIDIAN_FALL = event("block.endreborn.obsidian.fall");
    public static final SoundEvent CHORUS_WOOD_BREAK = event("block.endreborn.chorus_wood.break");
    public static final SoundEvent CHORUS_WOOD_STEP = event("block.endreborn.chorus_wood.step");
    public static final SoundEvent CHORUS_WOOD_PLACE = event("block.endreborn.chorus_wood.place");
    public static final SoundEvent CHORUS_WOOD_HIT = event("block.endreborn.chorus_wood.hit");
    public static final SoundEvent CHORUS_WOOD_FALL = event("block.endreborn.chorus_wood.fall");
    public static final SoundEvent AMBIENT_SHATTERED_BARRENS = event("ambient.endreborn.shattered_barrens.loop");
    public static final SoundEvent AMBIENT_VOID_GARDENS = event("ambient.endreborn.void_gardens.loop");
    public static final SoundEvent AMBIENT_OBSIDIAN_WASTES = event("ambient.endreborn.obsidian_wastes.loop");
    public static final SoundEvent AMBIENT_CRYSTAL_HIGHLANDS = event("ambient.endreborn.crystal_highlands.loop");
    public static final SoundEvent AMBIENT_ENDLESS_ABYSS = event("ambient.endreborn.endless_abyss.loop");
    public static final SoundEvent AMBIENT_CHORUS_JUNGLE = event("ambient.endreborn.chorus_jungle.loop");

    public static final SoundType VOID_STONE_SOUNDS = new SoundType(1.0F, 1.0F, VOID_STONE_BREAK, VOID_STONE_STEP, VOID_STONE_PLACE, VOID_STONE_HIT, VOID_STONE_FALL);
    public static final SoundType CRYSTAL_SOUNDS = new SoundType(1.0F, 1.0F, CRYSTAL_BREAK, CRYSTAL_STEP, CRYSTAL_PLACE, CRYSTAL_HIT, CRYSTAL_FALL);
    public static final SoundType OBSIDIAN_SOUNDS = new SoundType(1.0F, 1.0F, OBSIDIAN_BREAK, OBSIDIAN_STEP, OBSIDIAN_PLACE, OBSIDIAN_HIT, OBSIDIAN_FALL);
    public static final SoundType CHORUS_WOOD_SOUNDS = new SoundType(1.0F, 1.0F, CHORUS_WOOD_BREAK, CHORUS_WOOD_STEP, CHORUS_WOOD_PLACE, CHORUS_WOOD_HIT, CHORUS_WOOD_FALL);

    public static void register() {
        EndReborn.LOGGER.info("[EndReborn] Registered {} sound events.", 56);
    }
}
